#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} Worker secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# ──────────────────────────────────────────────────────────────────────────

# Wizard runs from the worker dir; store local values in .dev.vars (gitignored).
cd "$(dirname "$0")"
ENV_FILE=".dev.vars"

TOTAL_STAGES=5

banner "AI News Digest worker setup"

# Pages project (wrangler.toml: pages_build_output_dir = "static"). Secrets
# go via `wrangler pages secret put` — Workers-style `wrangler secret put`
# targets a different secret store and silently breaks POST /send (401).
PAGES_PROJECT="${PAGES_PROJECT:-ai-news-digest}"
put_worker_secret() {
  local name="$1" value="$2"
  if printf '%s' "$value" | npx wrangler pages secret put "$name" --project-name "$PAGES_PROJECT" >/dev/null 2>&1; then
    WRITTEN_SECRET+=("$name")
    printf '  %s✓ set%s Pages secret %s\n' "$GREEN" "$RESET" "$name"
  else
    SKIPPED+=("Pages secret $name (set it later: printf '...' | npx wrangler pages secret put $name --project-name $PAGES_PROJECT)")
    warn "skipped Worker secret $name — wrangler not ready; set it later"
  fi
}

# ── Stage 1: Resend sending domain ─────────────────────────────────────────
stage "Resend — verify the sending domain"
say "The digest sends from digest@nullzwo.dev. Resend must verify that domain."
open_url "https://resend.com/domains"
step "Confirm nullzwo.dev shows a verified/pending state in the Domains list."
step "If it isn't added yet: click 'Add Domain', enter nullzwo.dev, and follow the DNS steps."
note "If it's already verified (previous setup), there is nothing to do here."
confirm "Is digest@nullzwo.dev verified (or already set up) in Resend?" \
  || note "Fine — re-run later once it's verified; the rest still applies."

# ── Stage 2: Resend API key ────────────────────────────────────────────────
stage "Resend — create an API key"
say "Create a sending key — the worker uses it to email confirmations and to register contacts."
open_url "https://resend.com/api-keys"
step "Click 'Create API Key'. Pick a name (e.g. 'ai-news-worker')."
step "Copy the key — it is shown only once."
ask_secret RESEND_API_KEY "Paste the Resend API key:"
write_env RESEND_API_KEY "$RESEND_API_KEY"
put_worker_secret RESEND_API_KEY "$RESEND_API_KEY"

# ── Stage 3: SENDER value ──────────────────────────────────────────────────
stage "SENDER — confirmation email sender"
say "Used as the From address on the confirmation email."
note "Already verified: digest@nullzwo.dev"
ask SENDER "SENDER (Enter for default): "
[[ -z "$SENDER" ]] && SENDER="AI News Digest <digest@nullzwo.dev>"
write_env SENDER "$SENDER"

# ── Stage 4: Deploy ────────────────────────────────────────────────────────
stage "Deploy the worker"
say "Secrets are set. Next we deploy the worker to the edge."
step "The custom domain ai-news.nullzwo.dev is already declarative in wrangler.toml —",
step "so deploy attaches it automatically; no dashboard step needed."
confirm "Deploy now with npx wrangler deploy?" && {
  npx wrangler deploy
  printf '  %s✓%s deployed\n' "$GREEN" "$RESET"
} || note "Skipped deploy — run 'npx wrangler deploy' in worker/ when ready."

# ── Stage 5: Verify the live site ───────────────────────────────────────────
stage "Verify https://ai-news.nullzwo.dev"
say "Confirm the landing page is reachable on the custom domain."
open_url "https://ai-news.nullzwo.dev"
step "You should see the AI News Digest landing page with the email input."
confirm "Does the landing page load at https://ai-news.nullzwo.dev?" \
  || note "DNS may take a few minutes to propagate — re-run this stage later."

# ──────────────────────────────────────────────────────────────────────────
finish
